export enum SubtipoTEA {
  AUTISMO_CLASSICO = 'AUTISMO_CLASSICO',
  SINDROME_ASPERGER = 'SINDROME_ASPERGER',
  TRANSTORNO_DESINTEGRATIVO_DA_INFANCIA = 'TRANSTORNO_DESINTEGRATIVO_DA_INFANCIA',
  TRANSTORNO_DESENVOLVIMENTO_NAO_ESPECIFICADO = 'TRANSTORNO_DESENVOLVIMENTO_NAO_ESPECIFICADO',
}

export enum GravidadeTEA {
  LEVE = 'LEVE',
  MODERADA = 'MODERADA',
  GRAVE = 'GRAVE',
}
export enum Genero {
  MASCULINO = 'MASCULINO',
  FEMININO = 'FEMININO',
}
